// SetupWizard — first-run LLM configuration modal.
// Checks: settings.yaml has apiKey AND data/agents/ceo.json exists.
// If either is missing, shows a setup form before the main window.
// User must fill in + test connection, or the app quits.

import * as path from 'path';
import * as fs from 'fs';
import { app } from 'electron';
import type { BrowserWindow, IpcMain } from 'electron';

let _Bw: typeof BrowserWindow | null = null;
let _ipcMain: IpcMain | null = null;

export function init(BrowserWindow: typeof import('electron').BrowserWindow, ipcMain: IpcMain): void {
  _Bw = BrowserWindow;
  _ipcMain = ipcMain;
}

const appRoot = () => app.getAppPath();
/** In packaged mode, writable dirs are at app.asar.unpacked/. In dev mode, this is a no-op. */
const writableRoot = () => appRoot().replace(/\\/g, '/').includes('.asar') ? appRoot() + '.unpacked' : appRoot();

/**
 * Check if AnoClaw is already configured (first-run = needs setup).
 */
export function needsSetup(): boolean {
  const settingsPath = path.join(writableRoot(), 'config', 'settings.yaml');
  try {
    const raw = fs.readFileSync(settingsPath, 'utf-8');
    const hasKey = /apiKey\s*:\s*\S/.test(raw);
    if (!hasKey) return true;
  } catch {
    return true;
  }

  const agentPath = path.join(writableRoot(), 'data', 'agents', 'ceo.json');
  if (!fs.existsSync(agentPath)) return true;

  return false;
}

/**
 * Show the setup wizard. Returns a Promise that resolves when setup is complete,
 * or quits the app if the user cancels.
 */
export function runSetupWizard(): Promise<void> {
  return new Promise((resolve, reject) => {
    if (!_Bw || !_ipcMain) return reject(new Error('SetupWizard not initialized'));
    const ipc = _ipcMain;

    const htmlPath = path.join(appRoot(), 'src', 'electron', 'setup-wizard.html');
    const fallbackPath = path.join(appRoot(), 'dist', 'electron', 'setup-wizard.html');
    const finalHtmlPath = fs.existsSync(htmlPath) ? htmlPath :
      fs.existsSync(fallbackPath) ? fallbackPath : null;
    if (!finalHtmlPath) {
      return reject(new Error(`Setup wizard HTML not found`));
    }

    const win = new _Bw({
      width: 520,
      height: 680,
      minWidth: 420,
      minHeight: 560,
      resizable: true,
      maximizable: false,
      fullscreenable: false,
      title: 'AnoClaw Setup',
      frame: true,
      show: false,
      webPreferences: {
        preload: path.join(appRoot(), 'dist', 'electron', 'preload.cjs'),
        contextIsolation: true,
        nodeIntegration: false,
      },
    });

    win.setMenuBarVisibility(false);

    // ── IPC handlers ──
    ipc.handle('save-setup', async (_e: any, data: {
      agentName: string; model: string; apiUrl: string; apiKey: string;
      provider: string; contextWindow: number;
    }) => {
      try {
        const root = writableRoot(); // write to unpacked dir when packaged
        const provider = data.provider || 'openai-compatible';
        const ctxWindow = data.contextWindow || 131072;
        const apiUrl = provider === 'ollama' ? (data.apiUrl || 'http://localhost:11434')
          : provider === 'openai' ? 'https://api.openai.com'
          : provider === 'anthropic' ? 'https://api.anthropic.com'
          : data.apiUrl;

        // 1. Write settings.yaml
        const configDir = path.join(root, 'config');
        fs.mkdirSync(configDir, { recursive: true });
        const yaml = [
          '# AnoClaw Settings — auto-generated by setup wizard',
          `port: 3456`,
          `host: "127.0.0.1"`,
          `provider: "${provider}"`,
          `apiUrl: "${apiUrl}"`,
          `apiKey: "${data.apiKey}"`,
          `model: "${data.model}"`,
          '',
        ].join('\n');
        fs.writeFileSync(path.join(configDir, 'settings.yaml'), yaml, 'utf-8');

        // 2. Write MainAgent config
        const agentsDir = path.join(root, 'data', 'agents');
        fs.mkdirSync(agentsDir, { recursive: true });

        const { encryptApiKey } = await import('../server/core/agent/AgentConfig.js');
        const encryptedKey = data.apiKey ? encryptApiKey(data.apiKey) : '';
        const agentName = data.agentName || 'MainAgent';

        // Full CEO config — same as the dev template (data/agents/ceo.json)
        const agentConfig = {
          id: 'ceo',
          name: agentName,
          role: 'MainAgent',
          parentAgentId: null,
          level: 0,
          teamName: 'Executive',
          provider: provider,
          apiUrl: apiUrl,
          apiKey: encryptedKey,
          model: data.model,
          contextWindow: ctxWindow,
          maxTurns: 0,
          temperature: 0.7,
          agentPrompt: [
            `# ${agentName} — AnoClaw`,
            '',
            '## Identity',
            `You are ${agentName}. You run on AnoClaw — it is the platform, NOT your name.`,
            'Most tasks, you handle yourself — that\'s the whole point.',
            '',
            '## Decision Framework',
            '**Default: DO IT YOURSELF.** Single file or twenty — you have the tools.',
            '**Delegate ONLY when:** deep expertise lacking, parallel tracks needed, or specialist would do it better.',
            '',
            '## Communication',
            '- Talk to users in Chinese',
            '- Code and comments in English',
          ].join('\n'),
          preferredLanguage: 'en',
          conversationLanguage: 'zh',
          allowedTools: [
            'Read', 'Write', 'Edit', 'Glob', 'Grep', 'Bash',
            'WebFetch', 'WebSearch',
            'ListEmployees', 'HireEmployee', 'UpdateOrg',
            'TaskAssign', 'TaskList', 'TaskOutput', 'TaskStop',
            'SubAgentSpawn', 'SubAgentDelete',
            'TodoWrite', 'MemorySearch', 'MemorySave', 'MemoryDelete',
            'Skill', 'SkillList', 'ApiCall',
            'EnterPlanMode', 'ExitPlanMode',
            'RestartServer', 'AskUserQuestion',
            'LaunchMeeting', 'Workflow', 'Comfy',
          ],
          enabledSkills: [],
          mcpServers: [],
          state: 'Active',
          createdAt: new Date().toISOString(),
        };
        fs.writeFileSync(path.join(agentsDir, 'ceo.json'), JSON.stringify(agentConfig, null, 2), 'utf-8');

        return { ok: true };
      } catch (err) {
        return { ok: false, error: (err as Error).message };
      }
    });

    const onSetupDone = () => {
      ipc.removeHandler('save-setup');
      if (!win.isDestroyed()) win.close();
      resolve();
    };
    ipc.on('setup-done', onSetupDone);

    const onQuitSetup = () => {
      ipc.removeHandler('save-setup');
      if (!win.isDestroyed()) win.close();
      app.quit();
    };
    ipc.on('quit-setup', onQuitSetup);

    win.loadFile(finalHtmlPath);

    win.once('ready-to-show', () => {
      win.show();
      win.focus();
    });

    win.on('closed', () => {
      ipc.removeHandler('save-setup');
      ipc.removeAllListeners('setup-done');
      ipc.removeAllListeners('quit-setup');
    });
  });
}
