// SetupWizard - first-run LLM configuration modal.
// Configures the local v3 LLM credential boundary before the main window.
// No account, v2 Agent file, or cloud-side AnoClaw service is created.

import * as path from 'path';
import * as fs from 'fs';
import { app } from 'electron';
import type { BrowserWindow, IpcMain } from 'electron';

let _Bw: typeof BrowserWindow | null = null;
let _ipcMain: IpcMain | null = null;

export function init(BrowserWindow: typeof import('electron').BrowserWindow, ipcMain: IpcMain): void {
  _Bw = BrowserWindow;
  _ipcMain = ipcMain;
}

const appRoot = () => app.getAppPath();
/** In packaged mode, writable dirs are at app.asar.unpacked/. In dev mode, this is a no-op. */
const writableRoot = () => appRoot().replace(/\\/g, '/').includes('.asar') ? appRoot() + '.unpacked' : appRoot();

/**
 * Check if AnoClaw is already configured (first-run = needs setup).
 */
export function needsSetup(): boolean {
  const credentialPath = path.join(writableRoot(), 'config', 'credentials.v3.json');
  try {
    const parsed = JSON.parse(fs.readFileSync(credentialPath, 'utf-8')) as {
      schemaVersion?: number;
      credentialRef?: string;
      provider?: string;
      model?: string;
      encryptedApiKey?: string;
    };
    return parsed.schemaVersion !== 3
      || parsed.credentialRef !== 'local-llm'
      || !parsed.provider
      || !parsed.model
      || typeof parsed.encryptedApiKey !== 'string';
  } catch {
    return true;
  }
}

/**
 * Show the setup wizard. Returns a Promise that resolves when setup is complete,
 * or quits the app if the user cancels.
 */
export function runSetupWizard(): Promise<void> {
  return new Promise((resolve, reject) => {
    if (!_Bw || !_ipcMain) return reject(new Error('SetupWizard not initialized'));
    const ipc = _ipcMain;

    const htmlPath = path.join(appRoot(), 'src', 'electron', 'setup-wizard.html');
    const fallbackPath = path.join(appRoot(), 'dist', 'electron', 'setup-wizard.html');
    const finalHtmlPath = fs.existsSync(htmlPath) ? htmlPath :
      fs.existsSync(fallbackPath) ? fallbackPath : null;
    if (!finalHtmlPath) {
      return reject(new Error(`Setup wizard HTML not found`));
    }

    const win = new _Bw({
      width: 520,
      height: 680,
      minWidth: 420,
      minHeight: 560,
      resizable: true,
      maximizable: false,
      fullscreenable: false,
      title: 'AnoClaw Setup',
      frame: true,
      show: false,
      webPreferences: {
        preload: path.join(appRoot(), 'dist', 'electron', 'preload.cjs'),
        contextIsolation: true,
        nodeIntegration: false,
      },
    });

    win.setMenuBarVisibility(false);
    // IPC handlers
    ipc.handle('save-setup', async (_e: any, data: {
      agentName: string; model: string; apiUrl: string; apiKey: string;
      provider: string; contextWindow: number;
    }) => {
      try {
        const root = writableRoot(); // write to unpacked dir when packaged
        const provider = data.provider || 'openai-compatible';
        const ctxWindow = data.contextWindow || 131072;
        const apiUrl = provider === 'ollama' ? (data.apiUrl || 'http://localhost:11434')
          : provider === 'openai' ? 'https://api.openai.com'
          : provider === 'anthropic' ? 'https://api.anthropic.com'
          : data.apiUrl;

        // 1. Persist only non-secret runtime metadata in settings.yaml.
        const configDir = path.join(root, 'config');
        fs.mkdirSync(configDir, { recursive: true });
        const yaml = [
          '# AnoClaw 3 settings - auto-generated by local setup',
          `port: 3456`,
          `host: "127.0.0.1"`,
          `llm:`,
          `  provider: "${provider}"`,
          `  apiUrl: "${apiUrl}"`,
          `  model: "${data.model}"`,
          `  contextWindow: ${ctxWindow}`,
          `  credentialRef: "local-llm"`,
          '',
        ].join('\n');
        fs.writeFileSync(path.join(configDir, 'settings.yaml'), yaml, 'utf-8');

        // 2. Encrypt the API key in the dedicated v3 local credential store.
        const { LocalCredentialStore } = await import(
          '../server/core/v3/security/LocalCredentialStore.js'
        );
        await new LocalCredentialStore(
          path.join(configDir, 'credentials.v3.json'),
        ).save({
          credentialRef: 'local-llm',
          provider,
          apiUrl,
          model: data.model,
          contextWindow: ctxWindow,
          apiKey: data.apiKey || '',
        });

        return { ok: true };
      } catch (err) {
        return { ok: false, error: (err as Error).message };
      }
    });

    const onSetupDone = () => {
      ipc.removeHandler('save-setup');
      if (!win.isDestroyed()) win.close();
      resolve();
    };
    ipc.on('setup-done', onSetupDone);

    const onQuitSetup = () => {
      ipc.removeHandler('save-setup');
      if (!win.isDestroyed()) win.close();
      app.quit();
    };
    ipc.on('quit-setup', onQuitSetup);

    win.loadFile(finalHtmlPath);

    win.once('ready-to-show', () => {
      win.show();
      win.focus();
    });

    win.on('closed', () => {
      ipc.removeHandler('save-setup');
      ipc.removeAllListeners('setup-done');
      ipc.removeAllListeners('quit-setup');
    });
  });
}
