// SetupWizard - first-run LLM configuration modal.
// Checks: settings.yaml has apiKey and a MainAgent config exists.
// If either is missing, shows a setup form before the main window.
// User must fill in + test connection, or the app quits.

import * as path from 'path';
import * as fs from 'fs';
import { app } from 'electron';
import type { BrowserWindow, IpcMain } from 'electron';
import { DEFAULT_MAIN_AGENT_ID } from '../shared/constants.js';
import { buildDefaultAgentConfigs } from '../server/core/agent/DefaultAgentTemplate.js';
import type { AgentConfigWithKey } from '../server/core/agent/AgentConfig.js';

let _Bw: typeof BrowserWindow | null = null;
let _ipcMain: IpcMain | null = null;

export function init(BrowserWindow: typeof import('electron').BrowserWindow, ipcMain: IpcMain): void {
  _Bw = BrowserWindow;
  _ipcMain = ipcMain;
}

const appRoot = () => app.getAppPath();
/** In packaged mode, writable dirs are at app.asar.unpacked/. In dev mode, this is a no-op. */
const writableRoot = () => appRoot().replace(/\\/g, '/').includes('.asar') ? appRoot() + '.unpacked' : appRoot();

/**
 * Check if AnoClaw is already configured (first-run = needs setup).
 */
export function needsSetup(): boolean {
  const settingsPath = path.join(writableRoot(), 'config', 'settings.yaml');
  try {
    const raw = fs.readFileSync(settingsPath, 'utf-8');
    const hasKey = /apiKey\s*:\s*\S/.test(raw);
    if (!hasKey) return true;
  } catch {
    return true;
  }

  const agentsDir = path.join(writableRoot(), 'data', 'agents');
  const modernMainPath = path.join(agentsDir, `${DEFAULT_MAIN_AGENT_ID}.json`);
  const legacyMainPath = path.join(agentsDir, 'ceo.json');
  if (!fs.existsSync(modernMainPath) && !fs.existsSync(legacyMainPath)) return true;

  return false;
}

function filterKnownTools(config: AgentConfigWithKey, availableToolNames: Set<string> | null): AgentConfigWithKey {
  if (!availableToolNames) return config;
  return {
    ...config,
    allowedTools: config.allowedTools.filter((tool) => availableToolNames.has(tool)),
  };
}

/**
 * Show the setup wizard. Returns a Promise that resolves when setup is complete,
 * or quits the app if the user cancels.
 */
export function runSetupWizard(): Promise<void> {
  return new Promise((resolve, reject) => {
    if (!_Bw || !_ipcMain) return reject(new Error('SetupWizard not initialized'));
    const ipc = _ipcMain;

    const htmlPath = path.join(appRoot(), 'src', 'electron', 'setup-wizard.html');
    const fallbackPath = path.join(appRoot(), 'dist', 'electron', 'setup-wizard.html');
    const finalHtmlPath = fs.existsSync(htmlPath) ? htmlPath :
      fs.existsSync(fallbackPath) ? fallbackPath : null;
    if (!finalHtmlPath) {
      return reject(new Error(`Setup wizard HTML not found`));
    }

    const win = new _Bw({
      width: 520,
      height: 680,
      minWidth: 420,
      minHeight: 560,
      resizable: true,
      maximizable: false,
      fullscreenable: false,
      title: 'AnoClaw Setup',
      frame: true,
      show: false,
      webPreferences: {
        preload: path.join(appRoot(), 'dist', 'electron', 'preload.cjs'),
        contextIsolation: true,
        nodeIntegration: false,
      },
    });

    win.setMenuBarVisibility(false);
    // IPC handlers
    ipc.handle('save-setup', async (_e: any, data: {
      agentName: string; model: string; apiUrl: string; apiKey: string;
      provider: string; contextWindow: number;
    }) => {
      try {
        const root = writableRoot(); // write to unpacked dir when packaged
        const provider = data.provider || 'openai-compatible';
        const ctxWindow = data.contextWindow || 131072;
        const apiUrl = provider === 'ollama' ? (data.apiUrl || 'http://localhost:11434')
          : provider === 'openai' ? 'https://api.openai.com'
          : provider === 'anthropic' ? 'https://api.anthropic.com'
          : data.apiUrl;

        // 1. Write settings.yaml
        const configDir = path.join(root, 'config');
        fs.mkdirSync(configDir, { recursive: true });
        const yaml = [
          '# AnoClaw Settings - auto-generated by setup wizard',
          `port: 3456`,
          `host: "127.0.0.1"`,
          `provider: "${provider}"`,
          `apiUrl: "${apiUrl}"`,
          `apiKey: "${data.apiKey}"`,
          `model: "${data.model}"`,
          `contextWindow: ${ctxWindow}`,
          '',
        ].join('\n');
        fs.writeFileSync(path.join(configDir, 'settings.yaml'), yaml, 'utf-8');

        // 2. Write MainAgent config
        const agentsDir = path.join(root, 'data', 'agents');
        fs.mkdirSync(agentsDir, { recursive: true });

        const { encryptApiKey } = await import('../server/core/agent/AgentConfig.js');
        const agentName = data.agentName || 'MainAgent';

        // Read available tool names from the running ToolRegistry (already started)
        let availableToolNames: Set<string> | null = null;
        try {
          const { ToolRegistry } = await import('../server/core/tools/ToolRegistry.js');
          availableToolNames = new Set(ToolRegistry.getInstance().allToolNames());
        } catch {
          // ToolRegistry not available - use sensible defaults.
        }

        // Default agent organization, matching the dev first-run template.
        const configs = buildDefaultAgentConfigs({
          agentName,
          provider,
          apiUrl,
          apiKey: data.apiKey || '',
          model: data.model,
          contextWindow: ctxWindow,
        }).map((config) => filterKnownTools(config, availableToolNames));

        for (const config of configs) {
          fs.writeFileSync(
            path.join(agentsDir, `${config.id}.json`),
            JSON.stringify({ ...config, apiKey: config.apiKey ? encryptApiKey(config.apiKey) : '' }, null, 2),
            'utf-8',
          );
        }

        return { ok: true };
      } catch (err) {
        return { ok: false, error: (err as Error).message };
      }
    });

    const onSetupDone = () => {
      ipc.removeHandler('save-setup');
      if (!win.isDestroyed()) win.close();
      resolve();
    };
    ipc.on('setup-done', onSetupDone);

    const onQuitSetup = () => {
      ipc.removeHandler('save-setup');
      if (!win.isDestroyed()) win.close();
      app.quit();
    };
    ipc.on('quit-setup', onQuitSetup);

    win.loadFile(finalHtmlPath);

    win.once('ready-to-show', () => {
      win.show();
      win.focus();
    });

    win.on('closed', () => {
      ipc.removeHandler('save-setup');
      ipc.removeAllListeners('setup-done');
      ipc.removeAllListeners('quit-setup');
    });
  });
}
