import type { CapabilityDefinition } from '../../../shared/types/capability.js';

export function createDefaultCapabilityCatalog(): CapabilityDefinition[] {
  return [
    {
      id: 'presentation.create',
      title: 'Create a presentation',
      description: 'Create a slide deck such as a PPT, class deck, project report, or pitch deck.',
      domain: 'office',
      kind: 'artifact',
      triggers: [
        'ppt',
        'pptx',
        'presentation',
        'slides',
        'slide deck',
        'deck',
        '演示文稿',
        '幻灯片',
        '课件',
        '汇报',
        '路演',
      ],
      examples: [
        '帮我做一个介绍太阳系的小学生PPT',
        'Create a 10 slide investor pitch deck',
      ],
      inputs: [
        { name: 'topic', label: 'Topic', type: 'string', required: false },
        { name: 'audience', label: 'Audience', type: 'string', required: false, defaultValue: 'general audience' },
        { name: 'slideCount', label: 'Slide count', type: 'number', required: false, defaultValue: 10 },
        { name: 'style', label: 'Style', type: 'string', required: false, defaultValue: 'clear and professional' },
      ],
      outputs: [
        { type: 'file', label: 'PowerPoint deck', extension: 'pptx', artifactType: 'presentation' },
        { type: 'file', label: 'PDF export', extension: 'pdf', artifactType: 'document' },
        { type: 'preview', label: 'Slide previews', artifactType: 'image' },
      ],
      requiredTools: ['office.create_pptx'],
      artifactTypes: ['presentation', 'pptx'],
      recommendedPlugins: ['anoclaw-office'],
      priority: 100,
    },
    {
      id: 'document.create',
      title: 'Create a document',
      description: 'Write and export a Word-style document, report, proposal, contract draft, or letter.',
      domain: 'office',
      kind: 'artifact',
      triggers: ['document', 'docx', 'word', 'report', 'proposal', '合同', '报告', '文档', '申请书', '简历'],
      outputs: [
        { type: 'file', label: 'Word document', extension: 'docx', artifactType: 'document' },
        { type: 'file', label: 'PDF export', extension: 'pdf', artifactType: 'document' },
      ],
      requiredTools: ['office.create_docx'],
      artifactTypes: ['document', 'docx'],
      recommendedPlugins: ['anoclaw-office'],
      priority: 90,
    },
    {
      id: 'spreadsheet.analyze',
      title: 'Analyze a spreadsheet',
      description: 'Analyze CSV or Excel data and produce charts, summaries, and recommendations.',
      domain: 'data',
      kind: 'analysis',
      triggers: ['spreadsheet', 'excel', 'xlsx', 'csv', 'table', 'chart', '数据分析', '表格', '图表'],
      outputs: [
        { type: 'artifact', label: 'Analysis report', artifactType: 'report' },
        { type: 'file', label: 'Workbook', extension: 'xlsx', artifactType: 'spreadsheet' },
      ],
      requiredTools: ['Read', 'Write', 'Bash'],
      artifactTypes: ['spreadsheet', 'report'],
      recommendedPlugins: ['anoclaw-office', 'data-analysis'],
      priority: 80,
    },
    {
      id: 'pdf.summarize',
      title: 'Summarize a PDF',
      description: 'Read, summarize, and transform PDF files into notes, reports, or extracted data.',
      domain: 'pdf',
      kind: 'analysis',
      triggers: ['pdf', 'summarize pdf', 'extract pdf', 'PDF总结', '总结PDF', '阅读PDF'],
      outputs: [
        { type: 'artifact', label: 'Summary', artifactType: 'report' },
        { type: 'file', label: 'Extracted notes', extension: 'md', artifactType: 'document' },
      ],
      requiredTools: ['Read', 'Write'],
      recommendedPlugins: ['pdf'],
      priority: 75,
    },
    {
      id: 'web.research',
      title: 'Research the web',
      description: 'Search the web, collect sources, compare information, and produce a cited answer.',
      domain: 'web',
      kind: 'knowledge',
      triggers: ['search', 'research', 'look up', 'web', 'internet', '搜索', '查一下', '调研', '资料'],
      outputs: [
        { type: 'artifact', label: 'Research brief', artifactType: 'report' },
      ],
      requiredTools: ['WebSearch', 'WebFetch'],
      priority: 70,
    },
    {
      id: 'files.organize',
      title: 'Organize local files',
      description: 'Find, rename, classify, move, or summarize files in a workspace folder.',
      domain: 'files',
      kind: 'automation',
      triggers: ['organize files', 'rename files', 'folder', '整理文件', '重命名', '文件夹', '归档'],
      outputs: [
        { type: 'artifact', label: 'Change summary', artifactType: 'report' },
      ],
      requiredTools: ['Glob', 'Read', 'Write', 'Bash'],
      priority: 65,
    },
    {
      id: 'code.implement',
      title: 'Modify a codebase',
      description: 'Inspect a repository, change code, fix bugs, refactor, run tests, and summarize the result.',
      domain: 'coding',
      kind: 'automation',
      triggers: [
        'code',
        'coding',
        'programming',
        'implement',
        'fix bug',
        'refactor',
        'repository',
        'repo',
        'tests',
        '代码',
        '编程',
        '开发',
        '实现功能',
        '修 bug',
        '修复 bug',
        '重构',
        '跑测试',
      ],
      outputs: [
        { type: 'artifact', label: 'Change summary', artifactType: 'report' },
      ],
      requiredTools: ['Read', 'Edit', 'Write', 'Glob', 'Grep', 'Bash'],
      artifactTypes: ['code-change', 'report'],
      priority: 88,
    },
    {
      id: 'code.review',
      title: 'Review code',
      description: 'Review code changes, identify bugs and risks, and produce actionable findings.',
      domain: 'coding',
      kind: 'analysis',
      triggers: [
        'code review',
        'review code',
        'review pr',
        'pull request review',
        '代码审查',
        '代码评审',
        '评审代码',
        '审一下代码',
        '看一下这个 PR',
      ],
      outputs: [
        { type: 'artifact', label: 'Review findings', artifactType: 'report' },
      ],
      requiredTools: ['Read', 'Glob', 'Grep'],
      artifactTypes: ['code-review', 'report'],
      priority: 82,
    },
    {
      id: 'image.generate',
      title: 'Generate or edit an image',
      description: 'Create, edit, or transform a bitmap image for everyday visual work.',
      domain: 'image',
      kind: 'artifact',
      triggers: ['image', 'picture', 'photo', 'poster', 'logo', '生成图片', '改图', '海报', '照片'],
      outputs: [
        { type: 'file', label: 'Image', extension: 'png', artifactType: 'image' },
      ],
      requiredTools: ['image.generate'],
      artifactTypes: ['image'],
      recommendedPlugins: ['image'],
      priority: 60,
    },
    {
      id: 'education.explain',
      title: 'Explain a learning topic',
      description: 'Explain homework, math problems, science concepts, or reading material with child-friendly guidance.',
      domain: 'education',
      kind: 'knowledge',
      triggers: ['homework', 'math problem', 'explain to my child', 'teach', '作业', '数学题', '给孩子讲', '讲解', '辅导', '出题'],
      inputs: [
        { name: 'question', label: 'Question', type: 'string', required: false },
        { name: 'childAge', label: 'Child age', type: 'number', required: false },
      ],
      outputs: [
        { type: 'artifact', label: 'Learning explanation', artifactType: 'report' },
      ],
      requiredTools: ['education.explain'],
      recommendedPlugins: ['education'],
      priority: 58,
    },
    {
      id: 'memory.preference.save',
      title: 'Remember user preferences',
      description: 'Save durable preferences such as writing style, output format, family context, or work habits.',
      domain: 'memory',
      kind: 'memory',
      triggers: ['remember', 'preference', '以后', '记住', '偏好', '习惯'],
      outputs: [
        { type: 'artifact', label: 'Saved memory', artifactType: 'memory' },
      ],
      requiredTools: ['memory_save', 'memory_search'],
      priority: 50,
    },
  ];
}
