import type { CapabilityDefinition } from '../../../shared/types/capability.js';

export function createDefaultCapabilityCatalog(): CapabilityDefinition[] {
  return [
    {
      id: 'code.implement',
      title: 'Modify a codebase',
      description: 'Inspect a repository, change code, fix bugs, refactor, run tests, and summarize the result.',
      domain: 'coding',
      kind: 'automation',
      triggers: [
        'code',
        'coding',
        'programming',
        'implement',
        'fix bug',
        'refactor',
        'repository',
        'repo',
        'tests',
        '代码',
        '编程',
        '开发',
        '实现功能',
        '修 bug',
        '修复 bug',
        '重构',
        '跑测试',
      ],
      outputs: [
        { type: 'artifact', label: 'Change summary', artifactType: 'report' },
      ],
      requiredTools: ['Read', 'Edit', 'Write', 'Glob', 'Grep', 'Bash'],
      artifactTypes: ['code-change', 'report'],
      priority: 88,
    },
    {
      id: 'code.review',
      title: 'Review code',
      description: 'Review code changes, identify bugs and risks, and produce actionable findings.',
      domain: 'coding',
      kind: 'analysis',
      triggers: [
        'code review',
        'review code',
        'review pr',
        'pull request review',
        '代码审查',
        '代码评审',
        '评审代码',
        '审一下代码',
        '看一下这个 PR',
      ],
      outputs: [
        { type: 'artifact', label: 'Review findings', artifactType: 'report' },
      ],
      requiredTools: ['Read', 'Glob', 'Grep', 'Bash'],
      artifactTypes: ['code-review', 'report'],
      priority: 82,
    },
    {
      id: 'image.generate',
      title: 'Generate or edit an image',
      description: 'Create, edit, or transform a bitmap image for everyday visual work.',
      domain: 'image',
      kind: 'artifact',
      triggers: ['image', 'picture', 'photo', 'poster', 'logo', '生成图片', '改图', '海报', '照片'],
      outputs: [
        { type: 'file', label: 'Image', extension: 'png', artifactType: 'image' },
      ],
      requiredTools: ['image.generate'],
      artifactTypes: ['image'],
      recommendedPlugins: ['image'],
      priority: 60,
    },
    {
      id: 'education.explain',
      title: 'Explain a learning topic',
      description: 'Explain homework, math problems, science concepts, or reading material with child-friendly guidance.',
      domain: 'education',
      kind: 'knowledge',
      triggers: ['homework', 'math problem', 'explain to my child', 'teach', '作业', '数学题', '给孩子讲', '讲解', '辅导', '出题'],
      inputs: [
        { name: 'question', label: 'Question', type: 'string', required: false },
        { name: 'childAge', label: 'Child age', type: 'number', required: false },
      ],
      outputs: [
        { type: 'artifact', label: 'Learning explanation', artifactType: 'report' },
      ],
      requiredTools: ['education.explain'],
      recommendedPlugins: ['education'],
      priority: 58,
    },
    {
      id: 'memory.preference.save',
      title: 'Remember user preferences',
      description: 'Save durable preferences such as writing style, output format, family context, or work habits.',
      domain: 'memory',
      kind: 'memory',
      triggers: ['remember', 'preference', '以后', '记住', '偏好', '习惯'],
      outputs: [
        { type: 'artifact', label: 'Saved memory', artifactType: 'memory' },
      ],
      requiredTools: ['memory_save', 'memory_search'],
      priority: 50,
    },
  ];
}
